version: '3.1'
services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - some-net
  Golang:
    image: golang:1.18
    restart: always
    ports:
      - "8080:8080"
    build:
      context: ./go
      dockerfile: Dockerfile
    networks:
        - some-net
networks:
  some-net:
    driver: bridge